alkemyTech/OT166-Java-server

src/main/java/com/alkemy/ong/infrastructure/database/entity/SlideEntity.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/ISlideRepository.java

OT166-28: Crear modelo y repositorio de Slides

---

src/main/java/com/alkemy/ong/infrastructure/database/entity/CategoryEntity.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/ICategoryRepository.java

OT166-18: Creacion modelo y repositorio base de Categorias

---

src/main/java/com/alkemy/ong/infrastructure/database/entity/ActivityEntity.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/IActivityRepository.java

OT166-21# - Cree la entity y repository de Activities 

---

src/main/java/com/alkemy/ong/infrastructure/database/entity/OrganizationEntity.java

OT166-63: Agregar campos de contacto a organizations

---

src/main/java/com/alkemy/ong/infrastructure/database/entity/ContactEntity.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/IContactRepository.java

OT166-53: Crear modelo y repositorio de Contactos

---

src/main/java/com/alkemy/ong/infrastructure/database/entity/UserEntity.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/IUserRepository.java

OT166-17: Crear modelo y repositorio base de Users

---

src/main/java/com/alkemy/ong/infrastructure/spring/config/security/SecurityConfig.java

Se añadió el JWTfilter y está comentado por lo que se habló en la daily del jueves. 
* ...
* ...
* ....

OT166-73: Se añadió el JWTfilter (está comentado)

---

src/main/java/com/alkemy/ong/infrastructure/database/entity/CommentEntity.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/ICommentRepository.java

Model and repository created for Comments.
* ...
* ...
* ....

OT166-74: Crear modelo y repositorio de Comentarios

---

src/main/java/com/alkemy/ong/infrastructure/spring/config/security/SecurityConfig.java

- Create Authentication Manager
- Create and config AuthenticationEntryPoint
- 
* ...
* ...
* ....

OT166 33: Validar rol

---

pom.xml
src/main/java/com/alkemy/ong/application/exception/SendEmailException.java
src/main/java/com/alkemy/ong/application/util/mail/EmailDelegate.java
src/main/java/com/alkemy/ong/application/util/mail/IContent.java
src/main/java/com/alkemy/ong/application/util/mail/IEmail.java
src/main/resources/application.properties
src/test/java/com/alkemy/ong/bigtest/mail/SendMailIntegrationTest.java
src/test/resources/application.properties

Ticket OT166- 27 : Envío de Mails
- Add dependency SendGrid
- Creation of mail package (class emailDeleate, IEmail, IContent)
- Creation SendEmailException
* ...
* ...
* ....

Ot166 27 - Integrar Envío de Mails

---

etc/postman/OT166.postman_collection.json

OT166: Arreglos postman DEMO interna

---

src/main/java/com/alkemy/ong/application/rest/request/CreateContactRequest.java
src/main/java/com/alkemy/ong/application/rest/resource/ContactResource.java
src/main/java/com/alkemy/ong/application/rest/response/ContactResponse.java
src/main/java/com/alkemy/ong/application/service/ContactService.java
src/main/java/com/alkemy/ong/application/service/abstraction/ICreateContactService.java
src/main/java/com/alkemy/ong/infrastructure/database/entity/ContactEntity.java
src/main/java/com/alkemy/ong/infrastructure/database/mapper/abstraction/IContactMapper.java
src/main/java/com/alkemy/ong/infrastructure/spring/config/security/SecurityConfig.java

[[OT166-54](https://alkemy-labs.atlassian.net/browse/OT166-54)]
-Cambien la entidad Contact para que sea Null ya que tenia problemas al momento de insertar datos y como se registran datos el campo DeleteAt no es necesario
* ...
* ...
Test 1:
Test 2:
Test 3:

Ot166 54: Endpoint para almacenar contactos

---

etc/postman/OT166.postman_collection.json
src/main/java/com/alkemy/ong/application/rest/request/UpdateActivityRequest.java
src/main/java/com/alkemy/ong/application/rest/resource/ActivityResource.java
src/main/java/com/alkemy/ong/application/service/ActivityService.java
src/main/java/com/alkemy/ong/application/service/abstraction/IUpdateActivityService.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/IActivityRepository.java
src/main/java/com/alkemy/ong/infrastructure/spring/config/security/SecurityConfig.java

[#OT166-51](https://alkemy-labs.atlassian.net/browse/OT166-51)
* ...
* ...

OT166-51: Endpoint Actualización Actividades

---

etc/postman/OT166.postman_collection.json
src/main/java/com/alkemy/ong/application/rest/resource/CategoryResource.java
src/main/java/com/alkemy/ong/application/service/CategoryService.java
src/main/java/com/alkemy/ong/application/service/abstraction/IGetCategoryService.java
src/main/java/com/alkemy/ong/infrastructure/spring/config/security/SecurityConfig.java

Creación Endpoint Detalle Categoría
* ...
* ...
* ....

OT166 41 - Endpoint Detalle Categoría

---

src/main/java/com/alkemy/ong/application/rest/response/RegisterResponse.java
src/main/java/com/alkemy/ong/application/service/AuthenticationService.java

Modifica el metodo de login en la clase AuthenticacionService e hice un metodo para la autenticacion  para utilizarlo en login y register, tambien cambie el metodo de register en vez de regresar un registerresponse regrese un AuthenticationResponse para el token
* ...
* ...
* Test 1:

OT166-49: Devolver token al usuario luego de registrarse en el sitio

---

etc/postman/OT166.postman_collection.json
src/main/java/com/alkemy/ong/application/rest/resource/SlideResource.java
src/main/java/com/alkemy/ong/application/service/SlideService.java
src/main/java/com/alkemy/ong/application/service/abstraction/IGetSlideService.java
src/main/java/com/alkemy/ong/infrastructure/database/mapper/abstraction/ISlideMapper.java
src/main/java/com/alkemy/ong/infrastructure/spring/config/security/SecurityConfig.java

COMO usuario estándar o administrador
QUIERO ver el detalle de Slides
PARA ver el contenido de forma más detallada.
modificacion de SecurityConfig, SlideResource, SlideService, IGetSlideService, ISliderMapper
* ...
* ...

OT166-56: Endpoint Detalle Slides

---

etc/postman/OT166.postman_collection.json
src/main/java/com/alkemy/ong/application/rest/resource/ContactResource.java
src/main/java/com/alkemy/ong/application/rest/response/ListContactResponse.java
src/main/java/com/alkemy/ong/application/rest/response/ListContactsResponse.java
src/main/java/com/alkemy/ong/application/service/ContactService.java
src/main/java/com/alkemy/ong/application/service/abstraction/IGetContactService.java
src/main/java/com/alkemy/ong/infrastructure/database/mapper/abstraction/IContactMapper.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/IContactRepository.java
src/main/java/com/alkemy/ong/infrastructure/spring/config/security/SecurityConfig.java

* .
* ...
* Prueba 1: Todos los usuarios no tienen un deleteAt
* Prueba 2: Un usuario tiene deleteAt y no lo muestra 
*

OT166-61: Endpoint para listar contactos

---

src/test/java/com/alkemy/ong/bigtest/user/DeleteUserIntegrationTest.java
src/test/java/com/alkemy/ong/bigtest/user/ListActiveUsersIntegrationTest.java
src/test/java/com/alkemy/ong/bigtest/user/UpdateUserIntegrationTest.java

Testear el escenario de respuesta correcta, y escenarios de error, como ids inexistentes, validaciones, permisos, etc. 
Los test de integración deberán ser incluidos en la carpeta **/bigtest/user**. _Se deberá crear un archivo por cada endpoint a testear_. Se puede utilizar como base el test creado a modo de demostración.
En este caso, test unitarios son opcionales si el desarrollador quiere agregarlos.

OT166-90: Test: Endpoints /users

---

etc/postman/OT166.postman_collection.json
src/main/java/com/alkemy/ong/application/rest/resource/MemberResource.java
src/main/java/com/alkemy/ong/application/rest/response/ListMembersResponse.java
src/main/java/com/alkemy/ong/application/service/MemberService.java
src/main/java/com/alkemy/ong/application/service/abstraction/IGetMemberService.java
src/main/java/com/alkemy/ong/infrastructure/database/mapper/abstraction/IMemberMapper.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/IMemberRepository.java
src/main/java/com/alkemy/ong/infrastructure/spring/config/security/SecurityConfig.java

* ...
* ...
*Prueba1 listado de los miembros que tengan softDelete en false:
Prueba2 listado de los miembros que tengan softDelete en false:

OT166-68: listar miembros

---

etc/postman/OT166.postman_collection.json
src/main/java/com/alkemy/ong/application/rest/request/UpdateNewsRequest.java
src/main/java/com/alkemy/ong/application/rest/resource/NewsResource.java
src/main/java/com/alkemy/ong/application/service/NewsService.java
src/main/java/com/alkemy/ong/application/service/abstraction/IUpdateNewsService.java
src/main/java/com/alkemy/ong/infrastructure/spring/config/security/SecurityConfig.java

-Endpoint update news added
-Service update news added
-DTO request added
* ...
* ...
* ....

OT166-47: Endpoint Actualización Novedades

---

etc/postman/OT166.postman_collection.json
src/main/java/com/alkemy/ong/application/rest/request/UpdateCategoryRequest.java
src/main/java/com/alkemy/ong/application/rest/resource/CategoryResource.java
src/main/java/com/alkemy/ong/application/service/CategoryService.java
src/main/java/com/alkemy/ong/application/service/abstraction/IUpdateCategoryService.java
src/main/java/com/alkemy/ong/infrastructure/spring/config/security/SecurityConfig.java

OT166-43: Endpoint Actualización Categorías

---

src/main/java/com/alkemy/ong/application/service/CommentService.java

TICKET OT166-76
Utilizacion clase MessageFormat para ticket OT166-76
* ...
* ...
* ....

Utilizacion clase MessageFormat para ticket OT166-76

---

etc/postman/OT166.postman_collection.json
src/main/java/com/alkemy/ong/application/rest/resource/NewsResource.java
src/main/java/com/alkemy/ong/application/rest/response/ListNewsResponse.java
src/main/java/com/alkemy/ong/application/rest/response/PaginationResponse.java
src/main/java/com/alkemy/ong/application/service/NewsService.java
src/main/java/com/alkemy/ong/application/service/abstraction/IGetNewsService.java
src/main/java/com/alkemy/ong/application/util/PaginatedResultsRetrieved.java
src/main/java/com/alkemy/ong/infrastructure/database/mapper/abstraction/INewsMapper.java
src/main/java/com/alkemy/ong/infrastructure/database/repository/INewsRepository.java
src/main/java/com/alkemy/ong/infrastructure/spring/config/security/SecurityConfig.java
src/main/resources/application.properties

Agregar paginación a Novedades
* ...
* ...
* ....
Paginación 
Headers

OT166 81 Agregar paginación a Novedades

---

etc/postman/OT166.postman_collection.json
src/main/java/com/alkemy/ong/application/rest/resource/SlideResource.java
src/main/java/com/alkemy/ong/application/rest/response/ListSlidesResponse.java
src/main/java/com/alkemy/ong/application/rest/response/SlideResponse.java
src/main/java/com/alkemy/ong/application/service/SlideService.java
src/main/java/com/alkemy/ong/application/service/abstraction/IGetSlideService.java
src/main/java/com/alkemy/ong/infrastructure/database/mapper/abstraction/ISlideMapper.java
src/main/java/com/alkemy/ong/infrastructure/spring/config/security/SecurityConfig.java

Endpoint Listado de Slides
* ...
* ...
* ....

OT166 55: Endpoint Listado de Slides

---

src/test/java/com/alkemy/ong/bigtest/testimonial/CreateTestimonialIntegrationTest.java
src/test/java/com/alkemy/ong/bigtest/testimonial/DeleteTestimonialIntegrationTest.java
src/test/java/com/alkemy/ong/bigtest/testimonial/UpdateTestimonialIntegrationTest.java
src/test/java/com/alkemy/ong/bigtest/util/BigTest.java

Testear el escenario de respuesta correcta, y escenarios de error, como ids inexistentes, validaciones, permisos, etc.
Los test de integración deberán ser incluidos en la carpeta /bigtest/testimonial. Se deberá crear un archivo por cada endpoint a testear. Se puede utilizar como base el test creado a modo de demostración.
En este caso, test unitarios son opcionales si el desarrollador quiere agregarlos.
* ...
* ...

OT166-98: Test Testimonial CREATE, UPDATE, DELETE (Falta GET)

---

src/main/java/com/alkemy/ong/application/rest/resource/TestimonialResource.java

**Add documentation GET method in Testimonials**
https://alkemy-labs.atlassian.net/browse/OT166-88
* ...
* ...
* ....
GET method in Swagger

OT166-88: add documentation GET method in Testimonials

---

etc/postman/OT166.postman_collection.json
src/main/java/com/alkemy/ong/application/rest/resource/CommentResource.java
src/main/java/com/alkemy/ong/application/rest/response/ListCommentsResponse.java
src/main/java/com/alkemy/ong/application/service/CommentService.java
src/main/java/com/alkemy/ong/application/service/abstraction/IGetCommentService.java
src/main/java/com/alkemy/ong/infrastructure/database/mapper/ICommentMapper.java
src/main/java/com/alkemy/ong/infrastructure/spring/config/security/SecurityConfig.java

Summary :
-Comment listing service
-List Mappers for service
-DTO response
-Endpoint
* ...
* ...
* ....

OT166-75: Endpoint para listar Comentarios

---

src/main/java/com/alkemy/ong/application/rest/request/CreateCategoryRequest.java
src/main/java/com/alkemy/ong/application/rest/request/UpdateCategoryRequest.java
src/main/java/com/alkemy/ong/application/rest/resource/CategoryResource.java
src/main/java/com/alkemy/ong/application/rest/response/CategoryResponse.java

Summary:
-Documentation for category endpoints added
* ...
* ...
* ....

OT166-85: Agregar documentación a Categorías

---

src/main/java/com/alkemy/ong/application/service/CategoryService.java
src/main/java/com/alkemy/ong/application/service/MemberService.java
src/main/java/com/alkemy/ong/application/service/NewsService.java
src/main/java/com/alkemy/ong/application/service/TestimonialService.java
src/main/java/com/alkemy/ong/application/util/GenericSetPagination.java

Agregué generics para un método utilizado en la paginación que se repetía en varias clases. 
PD: Espero que google me haya traducido bien el título 😅 
Creo que no rompí nada 😁

Added generalization of a method used in paging

---

src/test/java/com/alkemy/ong/bigtest/category/CreateCategoryIntegrationTest.java
src/test/java/com/alkemy/ong/bigtest/category/DeleteCategoryIntegrationTest.java
src/test/java/com/alkemy/ong/bigtest/util/BigTest.java

Realicé los Test de Create and Delete
https://alkemy-labs.atlassian.net/browse/OT166-97
* ...
* ...
* ....

OT166-97: Test Category CREATE and DELETE 
